# Generated by Django 4.2.6 on 2023-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Жанр', 'Жанр'), ('Боевик', 'Боевик'), ('Романтика', 'Романтика')], default=('Жанр', 'Жанр'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
